server:
   port: 8888
   
################################## redis配置###############################
spring:
   redis:
      cluster:
         nodes: 120.24.4.145:6371,120.24.4.145:6372,120.24.4.145:6373,120.24.4.145:6374
         #设置key的生存时间，当key过期时，它会被自动删除；
         expire-seconds: 120
         #设置命令的执行时间，如果超过这个时间，则报错;
         command-timeout: 5000
         #读取时间超时
         so-timeout: 20000
         #出现异常最大重试次数
         max-attempts: 5
         password: root
         isSsl: false

